models/Rutinas.php
<?php

namespace app\models;

/**
 * This is the model class for table "rutinas".
 *
 * @property int $codigo
 * @property string|null $tipo
 * @property int|null $identrenadorpersonal
 *
 * @property Componen[] $componens
 * @property Entrenadorespersonales $identrenadorpersonal0
 */
class Rutinas extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'rutinas';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['identrenadorpersonal'], 'integer'],
            [['tipo'], 'string', 'max' => 50],
            [['identrenadorpersonal'], 'exist', 'skipOnError' => true, 'targetClass' => Entrenadorespersonales::class, 'targetAttribute' => ['identrenadorpersonal' => 'id']],
            
            [['tipo'], 'match', 'pattern' => '/^[a-zA-ZáéíóúÁÉÍÓÚüÜñÑ\s-]+$/i', 'message' => 'Formato incorrecto. Solo se admiten letras.'],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'codigo' => 'Código',
            'tipo' => 'Tipo',
            'identrenadorpersonal' => 'ID Entrenador Personal',
        ];
    }

    /**
     * Gets query for [[Componen]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getComponen()
    {
        return $this->hasMany(Componen::class, ['codrutina' => 'codigo']);
    }

    /**
     * Gets query for [[Identrenadorpersonal]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getIdentrenadorpersonal()
    {
        return $this->hasOne(Entrenadorespersonales::class, ['id' => 'identrenadorpersonal']);
    }
    
}

controllers/ComponenController.php
<?php

namespace app\controllers;

use app\models\Componen;
use app\models\Rutinas;
use app\models\Ejercicios;
use app\models\PostSearch\Componen as ComponenSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use kartik\mpdf\Pdf;
use Yii;


/**
 * ComponenController implements the CRUD actions for Componen model.
 */
class ComponenController extends Controller
{
    /**
     * @inheritDoc
     */
    public function behaviors()
    {
        return array_merge(
            parent::behaviors(),
            [
                'verbs' => [
                    'class' => VerbFilter::className(),
                    'actions' => [
                        'delete' => ['POST'],
                    ],
                ],
            ]
        );
    }

    /**
     * Lists all Componen models.
     *
     * @return string
     */
    public function actionIndex()
    {
        $searchModel = new ComponenSearch();
        $dataProvider = $searchModel->search($this->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Componen model.
     * @param int $id ID
     * @return string
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Componen model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return string|\yii\web\Response
     */
    public function actionCreate()
    {
        $model = new Componen();

        if ($this->request->isPost) {
            if ($model->load($this->request->post()) && $model->save()) {
                return $this->redirect(['view', 'id' => $model->id]);
            }
        } else {
            $model->loadDefaultValues();
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing Componen model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param int $id ID
     * @return string|\yii\web\Response
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($this->request->isPost && $model->load($this->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing Componen model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param int $id ID
     * @return \yii\web\Response
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    public function actionVolver()
    {
        return $this->redirect(['index']);
    }
    
    /**
     * Finds the Componen model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param int $id ID
     * @return Componen the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Componen::findOne(['id' => $id])) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('La página no existe.');
    }   
    
    public function actionDescargar($codigo)
    {
        Yii::$app->response->format = \yii\web\Response::FORMAT_RAW;
        Yii::$app->response->headers->add('Content-Type', 'application/pdf');

        // Obtener los códigos de los ejercicios relacionados con la rutina
        $componentes = Componen::find()
            ->where(['codrutina' => $codigo])
            ->all();

        // Obtener la rutina específica
        $rutina = Rutinas::findOne($codigo);
        if (!$rutina) {
            throw new NotFoundHttpException('Rutina no encontrada');
        }

        // Obtener los ejercicios completos
        $ejercicios = [];
        foreach ($componentes as $componente) {
            $ejercicio = Ejercicios::findOne($componente->codejercicio);
            if ($ejercicio !== null) {
                $ejercicios[] = $ejercicio;
            }
        }

        // Verificar si se encontraron los ejercicios
        if (empty($ejercicios)) {
            throw new NotFoundHttpException('Ejercicios no encontrados');
        }

        // Configurar el PDF
        $pdf = new Pdf([
            'mode' => Pdf::MODE_CORE,
            'destination' => Pdf::DEST_BROWSER,
            'content' => $this->renderPartial('descargaPDF', [
                'rutina' => $rutina,
                'componentes' => $componentes,
                'ejercicios' => $ejercicios,
            ]),
            'methods' => [
                'SetTitle' => 'Descargar rutina',
                'SetFooter' => ['|Página {PAGENO}|'],
            ]
        ]);

        return $pdf->render();
    }

    
}

controllers/RutinasController.php
<?php

namespace app\controllers;

use app\models\Rutinas;
use app\models\PostSearch\Rutinas as RutinasSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * RutinasController implements the CRUD actions for Rutinas model.
 */
class RutinasController extends Controller {

    /**
     * @inheritDoc
     */
    public function behaviors() {
        return array_merge(
                parent::behaviors(),
                [
                    'verbs' => [
                        'class' => VerbFilter::className(),
                        'actions' => [
                            'delete' => ['POST'],
                        ],
                    ],
                ]
        );
    }

    /**
     * Lists all Rutinas models.
     *
     * @return string
     */
    public function actionIndex() {
        $searchModel = new RutinasSearch();
        $dataProvider = $searchModel->search($this->request->queryParams);

        return $this->render('index', [
                    'searchModel' => $searchModel,
                    'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Rutinas model.
     * @param int $codigo Codigo
     * @return string
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($codigo) {
        return $this->render('view', [
                    'model' => $this->findModel($codigo),
        ]);
    }

    /**
     * Creates a new Rutinas model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return string|\yii\web\Response
     */
    public function actionCreate() {
        $model = new Rutinas();

        if ($this->request->isPost) {
            if ($model->load($this->request->post()) && $model->save()) {
                return $this->redirect(['view', 'codigo' => $model->codigo]);
            }
        } else {
            $model->loadDefaultValues();
        }

        return $this->render('create', [
                    'model' => $model,
        ]);
    }

    /**
     * Updates an existing Rutinas model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param int $codigo Codigo
     * @return string|\yii\web\Response
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($codigo) {
        $model = $this->findModel($codigo);

        if ($this->request->isPost && $model->load($this->request->post()) && $model->save()) {
            return $this->redirect(['view', 'codigo' => $model->codigo]);
        }

        return $this->render('update', [
                    'model' => $model,
        ]);
    }

    /**
     * Deletes an existing Rutinas model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param int $codigo Codigo
     * @return \yii\web\Response
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($codigo) {
        $this->findModel($codigo)->delete();

        return $this->redirect(['index']);
    }

    public function actionVolver()
    {
        return $this->redirect(['index']);
    }

    /**
     * Finds the Rutinas model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param int $codigo Codigo
     * @return Rutinas the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($codigo) {
        if (($model = Rutinas::findOne(['codigo' => $codigo])) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }

}

views/rutinas/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/** @var yii\web\View $this */
/** @var app\models\Rutinas $model */
/** @var yii\widgets\ActiveForm $form */
?>

<p>
    <?= Html::a('Volver', ['volver'], ['class' => 'btn btn-secondary']) ?>
</p>

<div class="rutinas-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'tipo')->textInput(['maxlength' => true, 'placeholder' => 'Ingrese el nombre de la rutina...', 'autocomplete' => 'off']) ?>

    <?= $form->field($model, 'identrenadorpersonal')->dropDownList(
        \yii\helpers\ArrayHelper::map(
            \app\models\Entrenadorespersonales::find()->all(),
            'id',
            function ($entrenador) {
                return $entrenador->nombrecompleto;
            }
        ),
        ['prompt' => 'Selecciona un entrenador personal']
    )->label('Entrenador Personal') ?>

    <div class="form-group">
        <?= Html::submitButton('Guardar', ['class' => 'btn btn-success']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/rutinas/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/** @var yii\web\View $this */
/** @var app\models\PostSearch\Rutinas $model */
/** @var yii\widgets\ActiveForm $form */
?>

<div class="rutinas-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'codigo') ?>

    <?= $form->field($model, 'tipo') ?>

    <?= $form->field($model, 'identrenadorpersonal') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-outline-secondary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/rutinas/create.php
<?php

use yii\helpers\Html;

/** @var yii\web\View $this */
/** @var app\models\Rutinas $model */

$this->title = 'Crear Rutina';

?>
<div class="rutinas-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/rutinas/index.php
<?php

use app\models\Rutinas;
use yii\helpers\Html;
use yii\helpers\Url;
use yii\grid\ActionColumn;
use yii\grid\GridView;

/** @var yii\web\View $this */
/** @var app\models\PostSearch\Rutinas $searchModel */
/** @var yii\data\ActiveDataProvider $dataProvider */

$this->title = 'Rutinas';

?>
<div class="rutinas-index">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Nueva Rutina', ['create'], ['class' => 'btn btn-success']) ?>
    </p>

    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'summary' => '',
        'columns' => [
            [
                'attribute' => 'tipo',
                'headerOptions' => ['style' => 'width: 400px;'],
            ],
            [
                'label' => 'Entrenador Personal', 'value' => function($model) {
                    $entrenadorPersonal = $model->getIdentrenadorpersonal()->one();
                    if ($entrenadorPersonal !== null) {
                        return $entrenadorPersonal->nombrecompleto;
                    } else {
                        return '(sin asignar)';
                    }
                },
                'headerOptions' => ['style' => 'width: 600px;'],
            ],
            [
                'class' => ActionColumn::className(),
                'urlCreator' => function ($action, Rutinas $model, $key, $index, $column) {
                    return Url::toRoute([$action, 'codigo' => $model->codigo]);
                },
                'headerOptions' => ['style' => 'width: 60px;'],
            ],
        ],
    ]); ?>


</div>

views/rutinas/update.php
<?php

use yii\helpers\Html;

/** @var yii\web\View $this */
/** @var app\models\Rutinas $model */

$this->title = 'Actualizando Rutina';

?>
<div class="rutinas-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/rutinas/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/** @var yii\web\View $this */
/** @var app\models\Rutinas $model */

$this->title = $model->tipo;

\yii\web\YiiAsset::register($this);
?>
<div class="rutinas-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Descargar rutina', ['componen/descargar','codigo' => $model->codigo], [
            'class'=>'btn btn-info',
            'target'=>'_blank',
            'data-toogle'=>'tooltip',
            'title'=>'Descargar rutina en PDF'
        ]) ?>
        <?= Html::a('Actualizar', ['update', 'codigo' => $model->codigo], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('Eliminar', ['delete', 'codigo' => $model->codigo], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => '¿Está seguro de eliminar este registro?',
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'tipo',
            [
                'label' => 'Entrenador Personal', 'value' => function($model) {
                    $entrenadorPersonal = $model->getIdentrenadorpersonal()->one();
                    if ($entrenadorPersonal !== null) {
                        return $entrenadorPersonal->nombrecompleto;
                    } else {
                        return '(sin asignar)';
                    }
                },
                'headerOptions' => ['style' => 'width: 600px;'],
            ],
        ],
    ]) ?>

</div>